project = ""
region = "asia-southeast1"
VPC = "projects/yourproject/global/networks/default"
VPCName = "default"
Subnet = "projects/yourproject/regions/asia-southeast1/subnetworks/default"
iapemail = "your@email.com"
domain = "your.domain.com"